const COVER_PHOTO_SELECTED = "COVER_PHOTO_SELECTED";
const PROFILE_PIC_SELECTED = "PROFILE_PIC_SELECTED";
const PICTURES_FETCHED = "PICTURES_FETCHED";

export { COVER_PHOTO_SELECTED, PICTURES_FETCHED, PROFILE_PIC_SELECTED };
